### ISSUE TITLE
Download links return "resource not found"

### ISSUE THREAD

**Issue by dlutz52** [thinktecture/Thinktecture.IdentityServer.v2#830]
Trying to download identity server from http://thinktecture.github.io/Thinktecture.IdentityServer.v2/downloads/ return ResourceNotFound for links to all three versions.

**Comment by brockallen** [comment]
Use the "Releases" link: https://github.com/thinktecture/Thinktecture.IdentityServer.v2/releases

**Comment by dlutz52** [comment]
Thank you, Brock, for the quick response. I was getting these links from a Google search after watching Dominick's courses on Identity in .NET 4.5 on Pluralsight. Issue now closed.
